version: '3.3'

services:
  webserver:
    image: traefik:v2.10

    ports:
      - 80:80

    labels:
      - traefik.enable=true
      - traefik.constraint-label=public
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.gzip.compress.excludedcontenttypes=image/png, image/jpeg, font/woff2

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `public`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --accesslog
      - --accesslog.format=json
      - --log
      - --log.level=DEBUG
      - --api

  frontend:
    image: ghcr.io/collective/plone-intranet-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    depends_on:
      - backend
    healthcheck:
      disable: true
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.constraint-label=public
      # Service
      - traefik.http.services.svc-frontend.loadbalancer.server.port=3000
      # Routers
      ## /
      - traefik.http.routers.rt-frontend.rule=Host(`intranet.localhost`)
      - traefik.http.routers.rt-frontend.entrypoints=http
      - traefik.http.routers.rt-frontend.service=svc-frontend
      - traefik.http.routers.rt-frontend.middlewares=gzip

  backend:
    image: ghcr.io/collective/plone-intranet-backend:latest
    environment:
      - OAUTH_AUTOMEMBER=1
      - OAUTH_AUTOADMIN=1
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.constraint-label=public
      # Services
      - traefik.http.services.svc-backend.loadbalancer.server.port=8080

      # Middlewares
      ## VHM rewrite /++api++/
      - "traefik.http.middlewares.mw-backend-vhm-api.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
      - "traefik.http.middlewares.mw-backend-vhm-api.replacepathregex.replacement=/VirtualHostBase/http/intranet.localhost/Plone/++api++/VirtualHostRoot/$$1"

      # Routes
      ## /++api++
      - traefik.http.routers.rt-backend-api.rule=Host(`intranet.localhost`) && (PathPrefix(`/++api++`))
      - traefik.http.routers.rt-backend-api.entrypoints=http
      - traefik.http.routers.rt-backend-api.service=svc-backend
      - traefik.http.routers.rt-backend-api.middlewares=gzip,mw-backend-vhm-api
      ## intranet-admin.localhost
      - traefik.http.routers.rt-backend-zmi.rule=Host(`intranet-admin.localhost`)
      - traefik.http.routers.rt-backend-zmi.entrypoints=http
      - traefik.http.routers.rt-backend-zmi.service=svc-backend
      - traefik.http.routers.rt-backend-zmi.middlewares=gzip
    volumes:
      - intranet-site-data:/data

volumes:
  intranet-site-data: {}
